version: "3.8"

services:
  books-service:
    build:
      context: .
      dockerfile: books-service/Dockerfile
    ports:
      - "5101:5001"
    depends_on:
      - mysql
    networks:
      - app-net

  users-service:
    build: 
      context: .
      dockerfile: users-service/Dockerfile
    ports:
      - "5102:5002"
    depends_on:
      - mysql
    networks:
      - app-net

  auth-service:
    build: 
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "5103:5003"
    depends_on:
      - mysql
    networks:
      - app-net

  gateway:
    image: nginx
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - books-service
      - users-service
      - auth-service
    networks:
      - app-net

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
